### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by ericksonlargura** [CorradiniGabriel/photosurferpage#1]
Your project is amazing, and you're doing great!

But you really should add a README to your project root, explaining what are you doing, and what are your project about.

Best regards!

**Comment by CorradiniGabriel** [comment]
Thank you mate! I will do that. Thank's for your guidance

**Comment by ericksonlargura** [comment]
Cool! I saw that you added a README in commit #[05c86a4](https://github.com/CorradiniGabriel/photosurferpage/commit/05c86a44b6d43bca721db8c21f77d768a1589f9f)

I'll close this issue now.
